#pragma once

#ifndef _KERNEL_MODE
#include <windows.h>
#include <winioctl.h>
#endif

#define RBX_DEVICE_TYPE 0x8000

#define IOCTL_ALLOCATE_MEMORY CTL_CODE(RBX_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_MEMORY    CTL_CODE(RBX_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROTECT_MEMORY  CTL_CODE(RBX_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FREE_MEMORY     CTL_CODE(RBX_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNLINK_VAD      CTL_CODE(RBX_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RELINK_VAD      CTL_CODE(RBX_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_MEMORY     CTL_CODE(RBX_DEVICE_TYPE, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _ALLOCATE_MEMORY_REQ {
    HANDLE TargetPid;
    SIZE_T Size;
    ULONG Protect;
    PVOID RemoteBase;
} ALLOCATE_MEMORY_REQ, *PALLOCATE_MEMORY_REQ;

typedef struct _WRITE_MEMORY_REQ {
    HANDLE TargetPid;
    PVOID RemoteBase;
    PVOID Buffer;
    SIZE_T Size;
} WRITE_MEMORY_REQ, *PWRITE_MEMORY_REQ;

typedef struct _READ_MEMORY_REQ {
    HANDLE TargetPid;
    PVOID RemoteBase;
    PVOID Buffer;
    SIZE_T Size;
} READ_MEMORY_REQ, *PREAD_MEMORY_REQ;

typedef struct _PROTECT_MEMORY_REQ {
    HANDLE TargetPid;
    PVOID RemoteBase;
    SIZE_T Size;
    ULONG NewProtect;
    ULONG OldProtect;
} PROTECT_MEMORY_REQ, *PPROTECT_MEMORY_REQ;

typedef struct _FREE_MEMORY_REQ {
    HANDLE TargetPid;
    PVOID RemoteBase;
    SIZE_T Size;
} FREE_MEMORY_REQ, *PFREE_MEMORY_REQ;

typedef struct _UNLINK_VAD_REQ {
    HANDLE TargetPid;
    PVOID RemoteBase;
    SIZE_T RegionSize;
} UNLINK_VAD_REQ, *PUNLINK_VAD_REQ;

typedef struct _RELINK_VAD_REQ {
    HANDLE TargetPid;
    PVOID RemoteBase;
} RELINK_VAD_REQ, *PRELINK_VAD_REQ;
